spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: sarana-resturant-system
  datasource:
    url: ${DB_NAME:jdbc:postgresql://localhost:5432/backend_360ss}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Phnom_Penh
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
  flyway:
   enabled: true
   baseline-on-migrate: true
   placeholders:
     defaultSchema: public
   rollback-locations: classpath:db/rollback
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:admin@123}
      timeout: 60000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000        # 10 minutes default TTL
      cache-null-values: false

server:
  tomcat:
    max-http-form-post-size: 104857600
    max-swallow-size: 104857600
  port: 8081

springdoc:
  api-docs:
    enabled: true

rustfs:
  endpoint: ${RUSTFS_ENDPOINT}
  access-key: ${RUSTFS_ACCESS_KEY}
  secret-key: ${RUSTFS_SECRET_KEY}
  bucket: ${RUSTFS_BUCKET}

app:
  jwt:
    secret: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg=
    access-expiration-seconds: 900
    refresh-expiration-seconds: 86400
