services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs_pro
    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: admin@123
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ADDRESS: ":9001"

    volumes:
      - rustfs_data:/data

    command: /data

volumes:
  rustfs_data:
#
#services:
#  minio:
#    image: quay.io/minio/minio:latest
#    container_name: phone_shop_minio
#    restart: unless-stopped
#
#    ports:
#      - "9000:9000"
#      - "9001:9001"
#
#    environment:
#      MINIO_ROOT_USER: admin
#      MINIO_ROOT_PASSWORD: admin@123
#
#    volumes:
#      - minio_data:/data
#
#    command: server /data --console-address ":9001"
#
#volumes:
#  minio_data: