CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_no VARCHAR(100),
    sale_id BIGINT,
    payment_method VARCHAR(255),
    bank_id BIGINT,
    amount NUMERIC(38, 2),
    transaction_no VARCHAR(255),
    status VARCHAR(50),
    payment_date TIMESTAMP,
    user_id BIGINT,
    created_at TIMESTAMP,
    created_by VARCHAR(100),
    updated_at TIMESTAMP,
    updated_by VARCHAR(100),
    deleted_at TIMESTAMP,
    deleted_by VARCHAR(100)
);

CREATE INDEX idx_payments_sale_id ON payments(sale_id);
CREATE INDEX idx_payments_payment_date ON payments(payment_date);
CREATE INDEX idx_payments_transaction_no ON payments(transaction_no);
CREATE INDEX idx_payments_bank_id ON payments(bank_id);