CREATE TABLE tbl_quote (
                           quote_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           date TIMESTAMP(6),
                           reference VARCHAR(100) NOT NULL UNIQUE,
                           no VARCHAR(100) NOT NULL UNIQUE,
                           customer_id BIGINT NOT NULL,
                           grand_total NUMERIC(19, 2),
                           discount NUMERIC(19, 2),
                           status VARCHAR(255),
                           status_payment VARCHAR(255),
                           paid_amount NUMERIC(19, 2),
                           return_amount NUMERIC(19, 2),
                           noted VARCHAR(255),
                           CONSTRAINT fk_quote_customer FOREIGN KEY (customer_id) REFERENCES tbl_customer(customer_id)
);

CREATE TABLE tbl_quote_items (
                                 id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                 product_id BIGINT NOT NULL,
                                 quote_id BIGINT,
                                 unit_quantity DECIMAL(19, 2),
                                 price DECIMAL(19, 2),
                                 discount_item DECIMAL(19, 2),
                                 subtotal DECIMAL(19, 2),
                                 CONSTRAINT fk_quote_items_product FOREIGN KEY (product_id) REFERENCES tbl_product(id),
                                 CONSTRAINT fk_quote_items_quote FOREIGN KEY (quote_id) REFERENCES tbl_quote(quote_id),
);