name: Telegram Notification

on:
  push:
    branches:
      - main
      - dev

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: "-1003966601591"
          token: "8008593219:AAHKG0hNi8pM-kR-g9mUOB631qiHZuByfjY"
          message_thread_id: "3"
          message: |
            📦 **New Push to GitHub**
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Pusher: ${{ github.actor }}
            Commit: ${{ github.event.head_commit.message }}